logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# rabbitMQ配置
spring:
  rabbitmq:
    host: 192.168.147.100
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 设置消费者预取的消息数量，每次只能获取一条消息，处理完成才能获取下一个消息